name: Build deployment AWS Lambdas as ZIP
on:
  push:
    branches:
      - 'main' 
      - 'master'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          
      - name: Echo intro message
        run: echo "Building packages"
        
      - name: Build project
        run: |
          pwd
          for func in collections popularity_proxy ; do
            cd ${func}
            if [[ -f "requirements.txt" ]]; then
              pip install --target . -r requirements.txt           
              rm -rf botocore*
              rm -rf boto3*
              rm -rf **/tests
              rm -rf **/__pycache__
            fi
            zip -r ${func}.zip .
            mv ${func}.zip ..
            cd ..
          done
          pwd
                   
      - name: Upload zip file artifact
        uses: actions/upload-artifact@v3
        with:
          name: collections
          path: collections.zip
