name: Build deployment AWS Lambdas as ZIP
on:
  push:
    branches:
      - 'main' 
      - 'master'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
        
      - name: Get AWS Wrangler as a zip file
        uses: wei/wget@v1
        with:
          args: -O awswrangler.zip https://github.com/aws/aws-sdk-pandas/releases/download/2.17.0/awswrangler-layer-2.17.0-py3.8.zip
          
      - name: Add python source code to AWS Wrangler zip
        run: |
          zip awswrangler.zip colections/app.py

      - name: Upload zip file artifact
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: awswrangler.zip
